import {BibFieldTypes, BibTypes} from "bibliojson"
import {
    Dialog,
    DialogTabs,
    InfoRow,
    addAlert
} from "fwtoolkit"
import type {DialogButtonSpec} from "fwtoolkit/dialog"
import {dateToYear, litToText, nameToText} from "../tools.js"
import type {
    BibDBCollection,
    BibDBEntry,
    BibliographyApp,
    FieldForm,
    FieldFormConstructor,
    FieldFormsMap,
    FormValue,
    IdTranslation,
    NameDictObject
} from "../types/biblio.js"
import {CatsForm} from "./cats.js"
import {DateFieldForm} from "./fields/date.js"
import {KeyFieldForm} from "./fields/key.js"
import {KeyListForm} from "./fields/key_list.js"
import {LiteralFieldForm} from "./fields/literal.js"
import {LiteralListForm} from "./fields/literal_list.js"
import {LiteralLongFieldForm} from "./fields/literal_long.js"
import {NameListForm} from "./fields/name_list.js"
import {RangeListForm} from "./fields/range_list.js"
import {TagListForm} from "./fields/tag_list.js"
import {TitleFieldForm} from "./fields/title.js"
import {URIFieldForm} from "./fields/uri.js"
import {VerbatimFieldForm} from "./fields/verbatim.js"
import {
    BibFieldHelp,
    BibFieldTitles,
    BibTypeTitles,
    getBibFieldTitle
} from "./strings.js"
import {bibDialog} from "./templates.js"

const FIELD_FORMS: FieldFormsMap = {
    f_date: DateFieldForm as FieldFormConstructor,
    f_integer: LiteralFieldForm as FieldFormConstructor,
    f_literal: LiteralFieldForm as FieldFormConstructor,
    l_literal: LiteralListForm as FieldFormConstructor,
    f_long_literal: LiteralLongFieldForm as FieldFormConstructor,
    f_key: KeyFieldForm as FieldFormConstructor,
    l_key: KeyListForm as FieldFormConstructor,
    l_name: NameListForm as FieldFormConstructor,
    l_range: RangeListForm as FieldFormConstructor,
    l_tag: TagListForm as FieldFormConstructor,
    f_title: TitleFieldForm as FieldFormConstructor,
    f_uri: URIFieldForm as FieldFormConstructor,
    f_verbatim: VerbatimFieldForm as FieldFormConstructor
}

export {BibFieldHelp, BibFieldTitles, BibTypeTitles, getBibFieldTitle}

export class BibEntryForm {
    bibDB: BibDBCollection
    itemId: number | false
    app: BibliographyApp | false
    fields: Record<string, FieldForm>
    currentValues: {
        bib_type: string | false
        cats: number[]
        entry_key: string
        fields: Record<string, unknown>
    }
    dialog?: Dialog
    dialogHeader?: string
    dialogTabs?: DialogTabs
    catsForm?: CatsForm
    entryKeyAutoGenerate = false
    programmaticallySettingKey = false
    lastAutoGeneratedKey: string | null = null

    constructor(
        bibDB: BibDBCollection,
        app: BibliographyApp | false = false,
        itemId: number | false = false
    ) {
        this.bibDB = bibDB
        this.itemId = itemId
        this.app = app
        this.fields = {}
        this.currentValues = {
            bib_type: false,
            cats: [],
            entry_key: "",
            fields: {}
        }
    }

    init(): Promise<IdTranslation[] | void> {
        if (this.app && this.app.isOffline()) {
            // Diable the editing of main user bibliography , since Document bibliography is stored in Editor/Document.
            addAlert(
                "info",
                gettext(
                    "You are currently offline. Please try again when you are back online."
                )
            )
            return Promise.resolve()
        }
        if (this.itemId !== false) {
            this.dialogHeader = gettext("Edit Source")
            const bibEntry = this.bibDB.db[this.itemId]
            this.currentValues = JSON.parse(JSON.stringify(bibEntry)) // copy current values
        } else {
            this.dialogHeader = gettext("Register New Source")
            this.currentValues = {
                bib_type: false,
                cats: [],
                entry_key: "",
                fields: {}
            }
        }
        return this.createForm()
    }

    addDialogToDOM(): Promise<IdTranslation[] | void> {
        // Add form to DOM
        const buttons: DialogButtonSpec[] = [
            {
                type: "close"
            }
        ]

        return new Promise(resolve => {
            buttons.push({
                classes: "fw-dark",
                text: gettext("Submit"),
                click: () => {
                    if (this.check()) {
                        const returnValue = this.save()
                        this.dialog!.close()
                        resolve(returnValue)
                    }
                }
            })

            this.entryKeyAutoGenerate = !this.currentValues.entry_key
            this.programmaticallySettingKey = false
            this.lastAutoGeneratedKey = null

            const hasCats = this.bibDB.cats.length > 0
            this.dialog = new Dialog({
                title: this.dialogHeader,
                id: "bib-dialog",
                width: 940,
                body: bibDialog({
                    bib_type: this.currentValues.bib_type,
                    bibTypes: BibTypes,
                    hasCats
                }),
                buttons
            })

            this.dialog.open()

            this.dialogTabs = new DialogTabs(
                [
                    {
                        id: "req-fields-tab",
                        title: gettext("Required Fields"),
                        template: () => ""
                    },
                    {
                        id: "opt-fields-tab",
                        title: gettext("Optional Fields"),
                        template: () => ""
                    },
                    ...(hasCats
                        ? [
                              {
                                  id: "categories-tab",
                                  title: gettext("Categories"),
                                  template: () => ""
                              }
                          ]
                        : [])
                ],
                {containerId: "bib-dialog-tabs"}
            )
            this.dialogTabs!.bind(
                this.dialog.dialogEl.querySelector("#bib-dialog-tabs") as HTMLElement
            )

            const entryKeyInput = document.getElementById(
                "entry-key"
            ) as HTMLInputElement | null
            if (entryKeyInput) {
                entryKeyInput.value = this.currentValues.entry_key || ""
                entryKeyInput.addEventListener("input", () => {
                    if (this.programmaticallySettingKey) {
                        return
                    }
                    this.entryKeyAutoGenerate = !entryKeyInput.value.trim()
                    if (this.entryKeyAutoGenerate) {
                        this.lastAutoGeneratedKey = null
                    }
                    this.checkEntryKey()
                })
                this.checkEntryKey()
                this.dialog.dialogEl.addEventListener("focusout", () => {
                    if (this.entryKeyAutoGenerate) {
                        this.maybeAutoGenerateEntryKey()
                    }
                })
            }

            ;(document.getElementById("select-bibtype") as HTMLElement)
                .addEventListener("change", () => resolve(this.changeBibType()))
        })
    }

    addField(fieldName: string, dom: HTMLElement): void {
        const fieldType = BibFieldTypes[fieldName]
        const fieldTitleText = getBibFieldTitle(
            fieldName,
            this.currentValues.bib_type || null
        )

        const row = new InfoRow({
            label: fieldTitleText,
            helpText: BibFieldHelp[fieldName],
            fieldClass: fieldName
        })
        dom.insertAdjacentHTML("beforeend", row.html())
        const fieldDOM = dom.lastChild!.lastChild as HTMLElement
        const FieldClass = FIELD_FORMS[fieldType.type]
        if (FieldClass) {
            const fieldHandler = new FieldClass(
                fieldDOM,
                this.currentValues.fields[fieldName],
                undefined,
                fieldType
            )
            fieldHandler.init()
            this.fields[fieldName] = fieldHandler
        }
    }

    createForm(): Promise<IdTranslation[] | void> {
        const dialogPromise = this.addDialogToDOM()
        if (this.currentValues.bib_type !== false) {
            const eitherOrFields = document.getElementById("eo-fields")!
            BibTypes[this.currentValues.bib_type].eitheror.forEach(
                fieldName => {
                    this.addField(fieldName, eitherOrFields)
                }
            )
            const reqFields = document.getElementById("req-fields")!
            BibTypes[this.currentValues.bib_type].required.forEach(
                fieldName => {
                    this.addField(fieldName, reqFields)
                }
            )
            const optFields = document.getElementById("opt-fields")!
            BibTypes[this.currentValues.bib_type].optional.forEach(
                fieldName => {
                    this.addField(fieldName, optFields)
                }
            )
            const catsField = document.getElementById("categories-field")
            if (catsField) {
                this.catsForm = new CatsForm(
                    catsField,
                    this.currentValues.cats,
                    this.bibDB.cats
                )
                this.catsForm.init()
            }
        }
        return dialogPromise
    }

    changeBibType(): Promise<IdTranslation[] | void> {
        // Add all current values into temporary currentValues, in case the
        // user still wants them.
        const formValue = this.value
        Object.assign(this.currentValues.fields, formValue.fields)
        this.currentValues.cats = formValue.cats as number[]
        this.currentValues.bib_type = formValue.bib_type
        // Reset fields and close dialog.
        this.fields = {}
        this.dialog!.close()
        return this.createForm()
    }

    createEntryKey(bibItem: FormValue): void {
        // We attempt to create a biblatex compatible entry key if there is no entry
        // key so far.
        let entryKey = ""
        if (bibItem.fields.author) {
            entryKey += nameToText(bibItem.fields.author as NameDictObject[]).replace(
                /\s|,|=|;|:|\{|}/g,
                ""
            )
        } else if (bibItem.fields.editor) {
            entryKey += nameToText(bibItem.fields.editor as NameDictObject[]).replace(
                /\s|,|=|;|:|\{|}/g,
                ""
            )
        }
        if (bibItem.fields.date) {
            entryKey += (bibItem.fields.date as string)
                .split("/")[0]
                .replace(/\?|\*|u|~|-/g, "")
        }
        if (entryKey.length) {
            bibItem.entry_key = entryKey
        }
    }

    maybeAutoGenerateEntryKey(): void {
        if (!this.entryKeyAutoGenerate) {
            return
        }
        const input = document.getElementById("entry-key") as HTMLInputElement | null
        if (!input) {
            return
        }
        const currentValue = input.value.trim()
        if (currentValue && currentValue !== this.lastAutoGeneratedKey) {
            return
        }

        let lastName = ""
        const nameField = this.fields.author || this.fields.editor
        if (
            nameField &&
            nameField.value &&
            (nameField.value as unknown[]).length
        ) {
            const firstAuthor = (nameField.value as NameDictObject[])[0]
            if (firstAuthor.family && firstAuthor.family.length) {
                lastName = litToText(firstAuthor.family)
            } else if (firstAuthor.literal && firstAuthor.literal.length) {
                lastName = litToText(firstAuthor.literal)
            }
        }
        lastName = lastName.replace(/[^a-zA-Z0-9_-]/g, "")

        let year = ""
        if (this.fields.date && this.fields.date.value) {
            const yearStr = dateToYear(this.fields.date.value as string)
            const yearMatch = yearStr.match(/-?(\d+)/)
            year = yearMatch ? yearMatch[1] : ""
        }
        year = year.replace(/[^a-zA-Z0-9_-]/g, "")

        const baseKey = `${lastName}${year}`
        if (!baseKey) {
            return
        }

        const existingKeys = new Set(
            Object.entries(this.bibDB.db)
                .filter(
                    ([id]) =>
                        Number.parseInt(id) !==
                        Number.parseInt((this.itemId || 0) as unknown as string)
                )
                .map(([, entry]) => entry.entry_key)
        )

        let key = baseKey
        let suffix = ""
        while (existingKeys.has(key + suffix)) {
            suffix =
                suffix === ""
                    ? "a"
                    : String.fromCharCode(suffix.charCodeAt(0) + 1)
        }
        key = key + suffix

        if (key === currentValue) {
            return
        }

        this.programmaticallySettingKey = true
        input.value = key
        this.programmaticallySettingKey = false
        this.lastAutoGeneratedKey = key
        this.checkEntryKey()
    }

    checkEntryKey(): void {
        const input = document.getElementById("entry-key") as HTMLInputElement | null
        const warningEl = document.getElementById("entry-key-warning")
        if (!input || !warningEl) {
            return
        }
        const value = input.value.trim()
        if (!value) {
            warningEl.textContent = ""
            return
        }
        const slugPattern = /^[a-zA-Z0-9_-]+$/
        if (!slugPattern.test(value)) {
            warningEl.textContent = gettext(
                "Only letters, numbers, hyphens and underscores are allowed."
            )
            return
        }
        // Check for duplicates in the user's library (soft requirement - just warn)
        const duplicate = Object.entries(this.bibDB.db).find(
            ([id, entry]) =>
                entry.entry_key === value &&
                Number.parseInt(id) !==
                    Number.parseInt((this.itemId || 0) as unknown as string)
        )
        if (duplicate) {
            warningEl.textContent = gettext(
                "Warning: this key is already used in your library."
            )
        } else {
            warningEl.textContent = ""
        }
    }

    get value(): FormValue {
        const entryKeyInput = document.querySelector("#entry-key") as HTMLInputElement | null
        const entryKey = entryKeyInput
            ? entryKeyInput.value.trim()
            : this.currentValues.entry_key
        const returnObj: FormValue = {
            bib_type: (document.querySelector("#select-bibtype") as HTMLSelectElement)
                .value,
            cats: this.catsForm ? this.catsForm.value : [],
            entry_key: entryKey,
            fields: {}
        }
        Object.keys(this.fields).forEach(fieldName => {
            const fieldValue = this.fields[fieldName].value
            if (fieldValue !== false) {
                returnObj["fields"][fieldName] = fieldValue
            }
        })
        return returnObj
    }

    save(): Promise<IdTranslation[]> {
        const isNew = this.itemId === false ? true : false,
            itemId = this.itemId === false ? 0 : this.itemId,
            item = this.value

        if (!item.entry_key) {
            this.createEntryKey(item)
        }
        const saveObj: Record<number, BibDBEntry> = {}
        saveObj[itemId] = item as unknown as BibDBEntry
        return this.bibDB.saveBibEntries(saveObj, isNew)
    }

    check(): boolean {
        let passed = true
        if (!this.currentValues.bib_type) {
            return false
        }
        Object.keys(this.fields).forEach(fieldName => {
            if (this.fields[fieldName].check() !== true) {
                passed = false
            }
        })
        if (!passed) {
            addAlert(
                "error",
                gettext("Error in form, check highlighted values!")
            )
        }
        return passed
    }
}
